In [1]:
# This file is using mean field approximation to solve this problem:
# Consider the Ising model on the n × n lattice as in Exercise 6.7 
# from [3] with the potentials modified to include a temperature-like 
# parameter β: P(x) = Z−1  i>j φ(xi,xj) with φ(xi,xj) = eβI[xi=xj] 
# for i a neighbour of j on a lattice and i > j (to avoid overcounting).
# You will need to compute the joint probability distribution of the top 
# and bot- tom nodes of the rightmost column of the 10 × 10 lattice. 
# If xi,j is the node in i-th row and j-th column, that would be nodes 
# x1,10 and x10,10, so you need to provide the probability table for 
# P(x1,10,x10,10). You have to do it for the threevaluesof β: β=4,β=1andβ=0.01. 

In [1]:
import numpy as np
def coordinateAscend(an):
    # in problem setting, the update function become a sigmoid
    return np.exp(an) / (1 + np.exp(an))

In [2]:
def mean_field_coordinate_ascend(beta, iteration, n):
    # I do zero padding so that I can easily perform neighbour interaction
    # in the same way as adding zero value does not effect the result
    field = np.random.uniform(0,1,(n+2,n+2))
    field[:,0] = 0
    field[:,-1] = 0
    field[0,:] = 0
    field[-1,:] = 0
    for i in range(iteration):
        for j in range(1,n+1):
            for k in range(1,n+1):
                an = beta * (field[j-1,k] + field[j+1,k] + field[j,k-1] + field[j,k+1])
                field[j,k] = coordinateAscend(an)
    return field

In [3]:
mean_field = mean_field_coordinate_ascend(1,1000,10)[1:11,1:11]
mean_field

array([[ 0.86814361,  0.94232189,  0.94627638,  0.94647863,  0.94648891,
         0.94648891,  0.94647863,  0.94627638,  0.94232189,  0.86814361],
       [ 0.94232189,  0.97904923,  0.97988147,  0.97990213,  0.97990274,
         0.97990274,  0.97990213,  0.97988147,  0.97904923,  0.94232189],
       [ 0.94627638,  0.97988147,  0.98056236,  0.98057599,  0.98057626,
         0.98057626,  0.98057599,  0.98056236,  0.97988147,  0.94627638],
       [ 0.94647863,  0.97990213,  0.98057599,  0.98058934,  0.9805896 ,
         0.9805896 ,  0.98058934,  0.98057599,  0.97990213,  0.94647863],
       [ 0.94648891,  0.97990274,  0.98057626,  0.9805896 ,  0.98058986,
         0.98058986,  0.9805896 ,  0.98057626,  0.97990274,  0.94648891],
       [ 0.94648891,  0.97990274,  0.98057626,  0.9805896 ,  0.98058986,
         0.98058986,  0.9805896 ,  0.98057626,  0.97990274,  0.94648891],
       [ 0.94647863,  0.97990213,  0.98057599,  0.98058934,  0.9805896 ,
         0.9805896 ,  0.98058934,  0.98057599

In [4]:
def get_prob(mean_field):
    joint_prob = np.zeros((2,2))
    joint_prob[0,0] = (1-mean_field[0,9]) * (1-mean_field[0,9])
    joint_prob[0,1] = (1-mean_field[0,9]) * mean_field[0,9]
    joint_prob[1,0] = mean_field[0,9] * (1-mean_field[0,9])
    joint_prob[1,1] = mean_field[0,9] * mean_field[0,9]
    return joint_prob

In [5]:
np.sum(get_prob(mean_field))

1.0

In [6]:
mean_field = mean_field_coordinate_ascend(0.01,1000,10)[1:11,1:11]
mean_field

array([[ 0.50251887,  0.50377829,  0.50378145,  0.50378145,  0.50378145,
         0.50378145,  0.50378145,  0.50378145,  0.50377829,  0.50251887],
       [ 0.50377829,  0.50504396,  0.50504714,  0.50504714,  0.50504714,
         0.50504714,  0.50504714,  0.50504714,  0.50504396,  0.50377829],
       [ 0.50378145,  0.50504714,  0.50505032,  0.50505032,  0.50505032,
         0.50505032,  0.50505032,  0.50505032,  0.50504714,  0.50378145],
       [ 0.50378145,  0.50504714,  0.50505032,  0.50505033,  0.50505033,
         0.50505033,  0.50505033,  0.50505032,  0.50504714,  0.50378145],
       [ 0.50378145,  0.50504714,  0.50505032,  0.50505033,  0.50505033,
         0.50505033,  0.50505033,  0.50505032,  0.50504714,  0.50378145],
       [ 0.50378145,  0.50504714,  0.50505032,  0.50505033,  0.50505033,
         0.50505033,  0.50505033,  0.50505032,  0.50504714,  0.50378145],
       [ 0.50378145,  0.50504714,  0.50505032,  0.50505033,  0.50505033,
         0.50505033,  0.50505033,  0.50505032

In [7]:
np.sum(get_prob(mean_field))

1.0

In [8]:
mean_field = mean_field_coordinate_ascend(4,1000,10)[1:11,1:11]
mean_field

array([[ 0.99966463,  0.99999385,  0.99999386,  0.99999386,  0.99999386,
         0.99999386,  0.99999386,  0.99999386,  0.99999385,  0.99966463],
       [ 0.99999385,  0.99999989,  0.99999989,  0.99999989,  0.99999989,
         0.99999989,  0.99999989,  0.99999989,  0.99999989,  0.99999385],
       [ 0.99999386,  0.99999989,  0.99999989,  0.99999989,  0.99999989,
         0.99999989,  0.99999989,  0.99999989,  0.99999989,  0.99999386],
       [ 0.99999386,  0.99999989,  0.99999989,  0.99999989,  0.99999989,
         0.99999989,  0.99999989,  0.99999989,  0.99999989,  0.99999386],
       [ 0.99999386,  0.99999989,  0.99999989,  0.99999989,  0.99999989,
         0.99999989,  0.99999989,  0.99999989,  0.99999989,  0.99999386],
       [ 0.99999386,  0.99999989,  0.99999989,  0.99999989,  0.99999989,
         0.99999989,  0.99999989,  0.99999989,  0.99999989,  0.99999386],
       [ 0.99999386,  0.99999989,  0.99999989,  0.99999989,  0.99999989,
         0.99999989,  0.99999989,  0.99999989

In [10]:
get_prob(mean_field)

array([[  1.12470778e-07,   3.35254161e-04],
       [  3.35254161e-04,   9.99329379e-01]])