## Matrix decomposition Multiplicative iteration

In [13]:
import numpy as np
m = 10
n = 5
V = np.random.randint(10,size = (m,n)).astype(float)
error_list = []
print(V)
for k in range(3,4):
    W = np.random.randint(5, size = (m,k)).astype(float)
    H = np.random.randint(5, size = (k,n)).astype(float)
    error = np.sum((V-W@H)**2)
    print(error)
    errors = [error]
    for i in range(50):
            H *= ((W.T@V) / (W.T@W@H))
            W *= ((V@H.T) / (W@H@H.T))
            print("Dimension: % d, Step: %d" % (k,i))
            print('H:')
            print(H)
            print('W:')
            print(W)
            print('diff:')
            print(V-W@H)
            error = np.sum((V-W@H)**2)
            errors.append(error)
    error_list.append(errors)

[[ 0.  6.  4.  8.  9.]
 [ 0.  7.  4.  2.  8.]
 [ 7.  9.  0.  3.  7.]
 [ 4.  6.  7.  8.  9.]
 [ 1.  2.  4.  4.  4.]
 [ 9.  6.  6.  5.  8.]
 [ 3.  4.  4.  2.  0.]
 [ 9.  0.  9.  6.  0.]
 [ 0.  5.  7.  4.  6.]
 [ 5.  4.  0.  3.  7.]]
6082.0
Dimension:  3, Step: 0
H:
[[ 0.48351648  0.93939394  0.          0.34638554  0.        ]
 [ 0.34101382  0.9         0.84158416  1.17220544  1.83629893]
 [ 0.69105691  0.          1.03773585  0.33691756  0.5371179 ]]
W:
[[ 3.04031904  4.11787644  0.85128634]
 [ 3.03454612  1.88117535  2.49743983]
 [ 4.47470215  2.97030196  1.22571962]
 [ 6.07239837  2.65262218  2.80921104]
 [ 0.          0.          4.26184194]
 [ 2.92623217  2.23150682  6.27461434]
 [ 4.03714036  0.          2.41343489]
 [ 2.07187653  1.71830541  3.5896785 ]
 [ 0.          3.24566876  2.07921114]
 [ 1.59614963  2.60090863  1.11343864]]
diff:
[[-3.46258448 -0.56214608 -0.34894993  1.83306697  0.98110676]
 [-3.83463292  2.45630796 -0.17485022 -2.09767822  3.20418007]
 [ 2.97645171  2.123

 [ 0.35981314 -1.5255654  -1.06706076  0.57903652  1.10154494]]
Dimension:  3, Step: 40
H:
[[  1.37220260e+00   3.24077976e-01   0.00000000e+00   1.23618312e-02
    0.00000000e+00]
 [  1.72453613e-03   1.68240340e+00   3.91047138e-01   8.95113855e-01
    2.24366216e+00]
 [  2.89404750e-01   0.00000000e+00   1.33938016e+00   9.18573394e-01
    2.28949875e-01]]
W:
[[  2.37198880e-05   3.86522977e+00   2.69031664e+00]
 [  1.26261775e-01   3.64442211e+00   5.16453749e-01]
 [  5.35444582e+00   3.46113446e+00   2.08082237e-05]
 [  1.83845118e+00   3.48185744e+00   4.57746994e+00]
 [  0.00000000e+00   0.00000000e+00   3.69049260e+00]
 [  5.71767428e+00   2.87972509e+00   3.37991564e+00]
 [  2.20384509e+00   0.00000000e+00   2.58254871e+00]
 [  4.87959131e+00   3.48909655e-08   6.56396802e+00]
 [  0.00000000e+00   2.45644101e+00   3.53893827e+00]
 [  3.38361710e+00   2.63213928e+00   8.86747988e-03]]
diff:
[[-0.78528869 -0.50288338 -1.11484375  2.06892571 -0.28821742]
 [-0.32900584  0.8276932 

In [14]:
error_list

[[6082.0,
  263.25415343071461,
  211.67529599521234,
  176.56085917891241,
  151.97870566081386,
  134.82144599150152,
  122.52676124003654,
  113.41409176647437,
  106.48387388829703,
  101.11238676993295,
  96.875270546780683,
  93.470292844799729,
  90.679320120717549,
  88.343935113456851,
  86.348346687038301,
  84.607539643635278,
  83.059085265982617,
  81.657360268447178,
  80.369336447487044,
  79.171429798628367,
  78.047101468102341,
  76.985017261762948,
  75.977634006603509,
  75.020114635218405,
  74.109494529956692,
  73.244037771545109,
  72.422736849579692,
  71.644923150344241,
  70.909966908051999,
  70.21705356237392,
  69.565029035904303,
  68.952310310179783,
  68.376860320400439,
  67.836227121524047,
  67.327645527653999,
  66.84819444345483,
  66.394995340524062,
  65.9654282224719,
  65.557333188613413,
  65.169161277631275,
  64.800041042213536,
  64.449739945620806,
  64.118521870443487,
  63.806928510064253,
  63.515533562797337,
  63.244724904986349,
  62